#!/usr/bin/env bash
# Installing nginx and configuring it + adding redirection
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "server {
    listen 80 ;
    listen [::]:80;
    root /var/www/html;
    index index.html;
    servername ;
    location /redirect_me {
        return 301 /;
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx reload
