#!/usr/bin/env bash
# Installing nginx and configuring it + adding redirection and error page
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
echo "server {
    listen 80 ;
    listen [::]:80;
    root /var/www/html;
    index index.html;
    server_name 52.91.182.154;
    error_page 404 /custom_404.html;
    location = /custom_404.html {
	root /var/wwx/html;
	internal;
    }
    location /redirect_me {
        return 301 /;
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
