#!/usr/bin/env bash
# Adding a custom HTTP Header to the web servers
sudo apt-get update
sudo apt-get install -y nginx
echo "server {
    listen 80 ;
    listen [::]:80;
    server_name $host;
    add_header X-Served-By $host;
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
