#!/usr/bin/env bash
# Configuring HAProxy
sudo apt-get -y update
sudo apt-get install -y haproxy
echo -e "frontend myapp_front\n\tbind *:80\n\tdefault_backend myapp_back\nbackend myapp_back\n\tbalance roundrobin\n\tserver 445918-web-01 52.91.182.154:80\n\tserver 445918-web-02 34.202.164.102:80" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
