#!/usr/bin/env bash
# Fixing the web server
sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
echo "server {
    listen 80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
