#!/usr/bin/env bash
# Using the internal variable ISF
file=/etc/passwd
IFS=:
while read -r line;
do
	set "$line"
	echo "The user $1 is part of the $3 gang, lives in $6 and rides $7. $4's place is protected by the passcode $2, more info about the user here: $5"
done < "$file"
