#!/usr/bin/env bash
# Running nginx as nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx stop
sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /var/lib/nginx
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo service nginx restart
